"""oneframework -- write a local-first Web/PWA/Android app in declarative Python."""

from __future__ import annotations

from .errors import DslError, OneFrameworkError, SchemaError, ValidationError
from .device import OnDevice, action
from .model.expr import UNSET, expr, item, record, view
from .model.fields import (
    Binary,
    Boolean,
    String,
    Text,
    Html,
    Email,
    Phone,
    Url,
    Password,
    Barcode,
    Percent,
    Rating,
    Image,
    Signature,
    Uuid,
    Color,
    Date,
    Datetime,
    Duration,
    Float,
    GeoPoint,
    Integer,
    Json,
    Many2many,
    Many2one,
    One2one,
    Monetary,
    One2many,
    Selection,
    Time,
    register_widget,
)
from .model.meta import Model
from .modules import Module, discover, load_all
from .app import App
from .ui.components import (
    Accordion, Button, Col, Delete, Filter, Create, Group, List, Logic, Menu, Open, Repeat, Row, Save, Search,
    Section,
    Sort,
    Icon, Label, Pill, Set, Tab, Tabs,
)
from .ui.screen import Screen
from .ui.view import View

__version__ = "0.1.0"

__all__ = [
    "expr",
    "Model",
    "View",
    "App",
    "Screen",
    "load_all",
    "discover",
    "Module",
    "register_widget",
    "String",
    "Text",
    "Html",
    "Email",
    "Phone",
    "Url",
    "Password",
    "Barcode",
    "Percent",
    "Rating",
    "Image",
    "Signature",
    "Uuid",
    "Integer",
    "Json",
    "Float",
    "Monetary",
    "Duration",
    "Boolean",
    "Selection",
    "Color",
    "Date",
    "Datetime",
    "Time",
    "Binary",
    "GeoPoint",
    "Many2one",
    "One2one",
    "One2many",
    "Many2many",
    "Row",
    "Repeat",
    "Col",
    "Group",
    "Accordion",
    "Section",
    "Tabs",
    "Label",
    "Pill",
    "Icon",
    "Set",
    "Tab",
    "List",
    "Menu",
    "Button",
    "Search",
    "Filter",
    "Sort",
    "Delete",
    "Open",
    "Create",
    "Save",
    "Logic",
    "OnDevice",
    "action",
    "record",
    "view",
    "item",
    "UNSET",
    "OneFrameworkError",
    "DslError",
    "SchemaError",
    "ValidationError",
]
